services:
  - docker:dind
stages:
  - build
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  # FIXME
  REGISTRY_URL: registry.gitlab.com/your/repository/url
  DOCKER_BUILD_ID: ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}
image: golang:1.15
cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

build_image:
  stage: build
  image: docker:git
  when: manual
  script:
    - echo "building myApi image"
    - docker login ${REGISTRY_URL} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker build -t ${REGISTRY_URL}:${DOCKER_BUILD_ID} -f cmd/api/Dockerfile .
    - docker push ${REGISTRY_URL}:${DOCKER_BUILD_ID}
    - docker tag ${REGISTRY_URL}:${DOCKER_BUILD_ID} ${REGISTRY_URL}:latest
    - docker push ${REGISTRY_URL}:latest
    - docker login ${REGISTRY_URL} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  only:
    - master